### ISSUE TITLE
Github Actions 手动触发 workflow

### ISSUE THREAD

**Issue by techiall** [techiall/Blog#79]
添加一个参数 `workflow_dispatch`，这样子就可以指定某条分支进行构建了

例子如下：

```
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

这样子就可以在 Actions 中看到选项了

![image](https://user-images.githubusercontent.com/22126304/115118656-da58c300-9fd6-11eb-89b4-c42b526bb529.png)

更多配置可以查看 Github 文档

* [https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
* [https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs)
